#!/bin/sh /etc/rc.common

START=99
STOP=10

NAME="subscribe"
PROG="$(find /usr/sbin/ -maxdepth 1 -name "${NAME}*" | head -1)"

writelog() {
	# echo "$(date "+%Y.%m.%d_%H%M%S") - ${1}" >>/tmp/$NAME.log
	logger -t ${NAME} "${1}"
}

start() {
	config_load "$NAME"
	local enabled
	config_get_bool enabled "config" "enabled" "0"
	[ "$enabled" -eq "1" ] || return 1
	local port host uuid auth subscribe
	config_get port "config" "port" "8066"
	config_get host "config" "host"
	config_get uuid "config" "uuid"
	config_get auth "config" "auth"
	config_get subscribe "config" "subscribe"
	# 构建运行参数
	set -- -p "$port"
	[ -n "${host}" ] && set -- "$@" -h "${host}"
	[ -n "${uuid}" ] && set -- "$@" -u "${uuid}"
	[ -n "${auth}" ] && set -- "$@" -a "${auth}"
	[ -n "${subscribe}" ] && set -- "$@" -s "${subscribe}"
	# 构建启动参数
	start-stop-daemon -S -q -b -x "$PROG" -- "$@"
	writelog "${NAME} Starting ..."
}

stop() {
	# kill -9 $(pgrep -f "${PROG}*" | sed "s/$$//g") 2>/dev/null
	start-stop-daemon -K -q -s KILL -x "$PROG" 2>/dev/null
	writelog "${NAME} stopped ..."
}