name: Actions Build Package

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      method:
        description: |
          选择编译方式?
        required: true
        default: "download"
        type: choice
        options:
          - docker
          - download
      
      sdk:
        description: |
          选择编译插件
        required: false
        default: "all"
        type: choice
        options:
          - Openwrt
          - Immortalwrt
      
      package:
        description: |
          选择编译插件
        required: false
        default: "all"
        type: choice
        options:
          - all
          - luci-app-mddns
          - luci-app-mddns-script
          - luci-app-subscribe
          - luci-app-opencode
          - luci-app-scriptrun
          - luci-app-napcatapi
          - luci-app-photopea
          - luci-app-bemfa-server
          - luci-app-wake-on-lan
          - luci-app-napcat
          - luci-app-cifs-mount2
          - luci-app-unishare
          - luci-app-v2ray-server
          - ports-status
          - api-static
          - sub-static
          - page-static
      
      version:
        description: |
          选择 OpenWrt 版本
        required: true
        default: "24.10"
        type: choice
        options:
          - "23.05"
          - "24.10"
      
      pack:
        description: |
          是否压缩打包成gz?
        required: false
        default: false
        type: boolean
      
      cnb:
        description: |
          是否上传CNB?
        required: false
        default: true
        type: boolean
      
      feeds:
        description: |
          是否禁用feeds?
        required: false
        default: true
        type: boolean  
      
      out:
        description: |
          是否详细输出?
        required: false
        default: true
        type: boolean
      
      cache:
        description: |
          是否清理缓存?
        required: false
        default: false
        type: boolean
      
jobs:
  call-sdk-docker:
    if: ${{ inputs.method == 'docker' }}
    uses: ./.github/workflows/Call-SDK-Docker.yml
    secrets: inherit
    with:
      cache: ${{ inputs.cache }}
      feeds: ${{ inputs.feeds }}
      out: ${{ inputs.out }}
      sdk: ${{ inputs.sdk }}
      package: ${{ inputs.package }}
      version: ${{ inputs.version }}
  
  call-sdk-download:
    if: ${{ inputs.method == 'download' }}
    uses: ./.github/workflows/Call-SDK-Download.yml
    secrets: inherit
    with:
      cache: ${{ inputs.cache }}
      feeds: ${{ inputs.feeds }}
      pack: ${{ inputs.pack }}
      out: ${{ inputs.out }}
      sdk: ${{ inputs.sdk }}
      cnb: ${{ inputs.cnb }}
      package: ${{ inputs.package }}
      version: ${{ inputs.version }}  